name: Update SBP Rates

on:
  schedule:
    - cron: "0 5 * * *"  # every day at 5:00 AM UTC
  workflow_dispatch: # allows manual run

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rates.json
          git commit -m "Auto update SBP rates [skip ci]" || echo "No changes"
          git push
